# Zomato Dataset Cleaning

In [73]:
import pandas as pd

In [74]:
data = pd.read_csv("zomato_dataset.csv")

In [75]:
data.head(2)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari

In [76]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [78]:
data.shape

(51717, 17)

## 1)Deleting the redundent columns

In [79]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [80]:
columns_to_keep = ['name', 'online_order', 'book_table', 'rate','dish_liked','approx_cost(for two people)']
columns_to_drop = ['url', 'address','votes','phone', 'location', 'rest_type','cuisines','reviews_list', 'menu_item','listed_in(type)', 'listed_in(city)']

In [81]:
data.shape

(51717, 17)

In [82]:
len(columns_to_keep)

6

In [83]:
len(columns_to_drop)

11

### 1st Way - Filtering Data

In [84]:
type(data["name"])

pandas.core.series.Series

In [85]:
columns_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [86]:
data[columns_to_keep]

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [87]:
new_data = data[columns_to_keep]

In [88]:
new_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

### 2nd way - Dropping the columns

In [89]:
data.drop(columns=columns_to_drop, inplace=True)

In [90]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

## Remnaming the columns

### 1)renaming one by one

In [91]:
data.rename(columns={'name':'name1','book_table':'book_table123'})
# data.rename(columns={'name':'name1'},inplace=True)

,name1,online_order,book_table123,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

### 2)renaming all at once

In [92]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [93]:
data.columns[0].capitalize()

'Name'

In [94]:
for i in data.columns:
    print(i.capitalize())

Name
Online_order
Book_table
Rate
Dish_liked
Approx_cost(for two people)

In [95]:
new_data_columns = []
for i in data.columns:
    new_data_columns.append(i.capitalize())

new_data_columns

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [96]:
data.columns = new_data_columns
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

## Droppinng the duplicates

In [97]:
data.duplicated().sum()

np.int64(32808)

In [98]:
data.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [99]:
data.duplicated().tail(10)

51707     True
51708     True
51709     True
51710     True
51711     True
51712     True
51713     True
51714    False
51715     True
51716     True
dtype: bool

In [100]:
data.drop_duplicates(inplace=True)

In [101]:
data.duplicated().sum()

np.int64(0)

## Removing the NaN values from the data sheet

In [102]:
data.isna()

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
51631,False,False,False,False,True,False
51632,False,False,False,False,True,False
51641,False,False,False,False,True,True
51677,False,False,False,False,False,False
51714,False,False,False,True,True,False

In [103]:
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [104]:
data.dropna(inplace=True)

In [105]:
data.isna().sum()

Name                           0
Online_order                   0
Book_table                     0
Rate                           0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [106]:
data = data.reset_index(drop=True)
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

## Cleaning Individual Columns

In [107]:
data["Rate"][12]

'4.0/5'

In [108]:
type(data["Rate"][12])

str

In [109]:
data["Rate"]

0        4.1/5
1        4.1/5
2        3.8/5
3        3.7/5
4        3.8/5
         ...
8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, Length: 8250, dtype: object

In [110]:
data["Rate"] = data["Rate"].str.replace(' ','')
data["Rate"]

0       4.1/5
1       4.1/5
2       3.8/5
3       3.7/5
4       3.8/5
        ...
8245    2.5/5
8246    3.6/5
8247    3.8/5
8248    4.2/5
8249    2.5/5
Name: Rate, Length: 8250, dtype: object

In [111]:
data["Rate"] = data["Rate"].str.replace('/5','')
data["Rate"]

0       4.1
1       4.1
2       3.8
3       3.7
4       3.8
       ...
8245    2.5
8246    3.6
8247    3.8
8248    4.2
8249    2.5
Name: Rate, Length: 8250, dtype: object

## Check for somemore transformations

In [112]:
data["Online_order"]

0       Yes
1       Yes
2       Yes
3        No
4        No
       ...
8245     No
8246     No
8247    Yes
8248     No
8249     No
Name: Online_order, Length: 8250, dtype: object

In [113]:
data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0 )

0       1
1       1
2       1
3       0
4       0
       ..
8245    0
8246    0
8247    1
8248    0
8249    0
Name: Online_order, Length: 8250, dtype: int64

In [114]:
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0 )

In [115]:
data

,Name,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7,Masala Dosa,300
4,Grand Village,0,No,3.8,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5,Manchow Soup,800
8246,Breakfast House,0,No,3.6,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5,"Biryani, Andhra Meal",800

In [116]:
data.to_csv("Cleaned_zomata_data.csv", index = False)

## Generating Insights

In [2]:
# data
data.columns

NameError: name 'data' is not defined

In [ ]:
data["Rate"] = pd.to_numeric(data["Rate"], errors="coerce")
data["Rate"] = pd.to_numeric(data["Rate"], errors="coerce")

In [ ]:
# Average ratings, cost, and popularity
print("Average Rating:", data["Rate"].mean())
print("Average Cost for Two:", data["Approx_cost(for two people)"].mean())
print("Total Restaurants:", data["Name"].nunique())

In [ ]:
# Top restaurant types by rating

top_types = (
    df.groupby("rest_type")["rate"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(top_types)

In [ ]:
# Most common cuisines
top_cuisines = df["cuisines"].value_counts().head(10)
print(top_cuisines)

In [ ]:
import matplotlib.pyplot as plt

location_counts.plot(kind="bar")
plt.title("Top Restaurant Locations")
plt.xlabel("Location")
plt.ylabel("Number of Restaurants")
plt.xticks(rotation=45)
plt.show()